### ISSUE TITLE
PXE and Kickstart File Selection in Configs

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#143]
Currently, to specify non-default PXE and kickstart files for a node/group, arguments to `metal build` are required. While this works it could be more flexible to allow for groups to contain nodes which are built from different PXE/kickstart files. The idea here is to move the definitions of these files to the configs, such that `domain.yaml` would contain lines like:

```
build:
  pxe: default
  kickstart: default
```

**Comment by WilliamMcCumstie** [comment]
Should be straight forward enough to do so. However would it be beneficial to include that as part of the `metal configure` commands?

**Comment by ColonelPanicks** [comment]
Brilliant. Would definitely be helpful for `configure group` and `configure node` to prompt for PXE/kickstart files.

**Comment by bobwhitelock** [comment]
@WilliamMcCumstie: if we define this in the `repo/config/` files then we can define them in terms of answers and have `metal configure` set these as needed

**Comment by WilliamMcCumstie** [comment]
@bobwhitelock, yeah we can do that. Ultimately that is all defined in `metalware-default`, so we should allow flexibility in that regard. I think the most important part is to check the `combined-hash` for some magic `pxelinux` and `kickstart` variable. 

Where you thinking something like:
```
build:
  pxelinux_template: <%= alces.answers.pxelinux_template %>
```

**Comment by bobwhitelock** [comment]
@WilliamMcCumstie: Yep, we can do something like

```yaml
build:
  pxelinux_template: <%= alces.answers.pxelinux_template %>
  kickstart_template: <%= alces.answers.kickstart_template %>
```

or like

```yaml
build:
  pxelinux_template: <%= alces.answers.build_template %>
  kickstart_template: <%= alces.answers.build_template %>
```

if we want to switch the template based on a single question for both; or we can make them dependent on other question answers.
