### ISSUE TITLE
Choices not displaying default/existing answer

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#199]
The below snip from `metal configure domain` shows how a choice question is displayed
```
1. hosts
2. named
DNS type to use for cluster (6/23)
```
Not only is the default set for this question in `configure.yaml`:
```
  - &dns_type
    identifier: dns_type
    question: 'DNS type to use for cluster'
    default: 'hosts'
    choices:
      - 'hosts'
      - 'named'
```
But there is also an existing answer in `answers/domain.yaml`:
```
dns_type: named
```

**Comment by WilliamMcCumstie** [comment]
So the default is being used by `Metalware`. I can tell because changing the `configure.yaml` to:
```
  - &dns_type
    identifier: dns_type
    question: 'DNS type to use for cluster'
    #default: 'hosts'
    choices:
      - 'hosts'
      - 'named'
```
Causes the question to be re asked as it doesn't have a response:
```
1. hosts
2. named
DNS type to use for cluster (6/23)

Your answer isn't valid (must match a non-empty input).
?  1. hosts
2. named
DNS type to use for cluster (6/23)
```
