### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/metalware#293]
The following test sometimes fails when running the spec. It might be a race condition or interaction with another test. Currently I just rerun the `travis` until it passes, however we should try and get to the bottom of it.

```

Failures:
  1) `metal build` for gender group interrupt handling with mocked highline handles "no" to interrupt prompt
     Failure/Error: FileUtils.touch(path)
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /var/lib/metalware/events/testnode01/complete
     # ./spec/integration/build_spec.rb:118:in `touch_complete_file'
     # ./spec/integration/build_spec.rb:271:in `block (6 levels) in <top (required)>'
     # ./spec/integration/build_spec.rb:89:in `block in build_node'
     # ./spec/filesystem.rb:91:in `block in test'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:86:in `with'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:111:in `FakeFS'
     # ./spec/filesystem.rb:85:in `test'
     # ./spec/filesystem.rb:227:in `test'
     # ./spec/integration/build_spec.rb:76:in `build_node'
     # ./spec/integration/build_spec.rb:267:in `block (5 levels) in <top (required)>'
     # ./spec/spec_helper.rb:152:in `block (3 levels) in <top (required)>'
     # ./spec/filesystem.rb:91:in `block in test'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:86:in `with'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:111:in `FakeFS'
     # ./spec/filesystem.rb:85:in `test'
     # ./spec/spec_helper.rb:151:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Errno::ENOENT:
     #   No such file or directory @ utime_internal - /var/lib/metalware/events/testnode01/complete
     #   ./spec/integration/build_spec.rb:118:in `touch_complete_file'
```

**Comment by WilliamMcCumstie** [comment]
There seems to be a couple:
```

Failures:
  1) `metal build` for gender group interrupt handling with mocked highline handles "no" to interrupt prompt
     Failure/Error: FileUtils.mkdir_p File.dirname(path)
     
     Errno::EACCES:
       Permission denied @ dir_s_mkdir - /var/lib/metalware
     # ./spec/integration/build_spec.rb:117:in `touch_complete_file'
     # ./spec/integration/build_spec.rb:271:in `block (6 levels) in <top (required)>'
     # ./spec/integration/build_spec.rb:89:in `block in build_node'
     # ./spec/filesystem.rb:91:in `block in test'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:86:in `with'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:111:in `FakeFS'
     # ./spec/filesystem.rb:85:in `test'
     # ./spec/filesystem.rb:227:in `test'
     # ./spec/integration/build_spec.rb:76:in `build_node'
     # ./spec/integration/build_spec.rb:267:in `block (5 levels) in <top (required)>'
     # ./spec/spec_helper.rb:152:in `block (3 levels) in <top (required)>'
     # ./spec/filesystem.rb:91:in `block in test'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:86:in `with'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:111:in `FakeFS'
     # ./spec/filesystem.rb:85:in `test'
     # ./spec/spec_helper.rb:151:in `block (2 levels) in <top (required)>'
```

**Comment by bobwhitelock** [comment]
Just came here to log the same issue, I agree we should fix this at some point :+1:

**Comment by bobwhitelock** [comment]
https://github.com/alces-software/metalware/issues/309#issue-296426630 is also another intermittent failure of the same flaky test.

**Comment by bobwhitelock** [comment]
Our most common intermittent failures at the moment are ones like the following:

```
Randomized with seed 54737
.....................................Run the complete_hook for nodes as if build succeeded?
[yes/no]
.Run the complete_hook for nodes as if build succeeded?
[yes/no]
..................................................................................................................................................................................................................................................................................................................................................................................................................F..F...........
Failures:
  1) Metalware::BuildEvent#process with a single node built deletes the build file
     Failure/Error: test_obj.process
     
     Errno::ENOENT:
       No such file or directory @ unlink_internal - /var/lib/metalware/events/node02/complete
     # ./src/build_event.rb:86:in `process_event_file'
     # ./src/build_event.rb:56:in `block in nodes_complete'
     # ./src/build_event.rb:53:in `delete_if'
     # ./src/build_event.rb:53:in `nodes_complete'
     # ./src/build_event.rb:20:in `process'
     # ./spec/build_event_spec.rb:65:in `block in process'
     # ./spec/alces_utils.rb:86:in `redirect_std'
     # ./spec/build_event_spec.rb:64:in `process'
     # ./spec/build_event_spec.rb:80:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:145:in `block (3 levels) in <top (required)>'
     # ./spec/filesystem.rb:117:in `block in test'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:86:in `with'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:111:in `FakeFS'
     # ./spec/filesystem.rb:111:in `test'
     # ./spec/spec_helper.rb:144:in `block (2 levels) in <top (required)>'
  2) Metalware::BuildEvent#process with all the nodes built deletes all the build files
     Failure/Error: test_obj.process
     
     Errno::ENOENT:
       No such file or directory @ unlink_internal - /var/lib/metalware/events/nodes4/complete
     # ./src/build_event.rb:86:in `process_event_file'
     # ./src/build_event.rb:56:in `block in nodes_complete'
     # ./src/build_event.rb:53:in `delete_if'
     # ./src/build_event.rb:53:in `nodes_complete'
     # ./src/build_event.rb:20:in `process'
     # ./spec/build_event_spec.rb:65:in `block in process'
     # ./spec/alces_utils.rb:86:in `redirect_std'
     # ./spec/build_event_spec.rb:64:in `process'
     # ./spec/build_event_spec.rb:108:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:145:in `block (3 levels) in <top (required)>'
     # ./spec/filesystem.rb:117:in `block in test'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:86:in `with'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/fakefs-0.11.3/lib/fakefs/base.rb:111:in `FakeFS'
     # ./spec/filesystem.rb:111:in `test'
     # ./spec/spec_helper.rb:144:in `block (2 levels) in <top (required)>'
```

These look like they have the same underlying cause.

The seed is shown above although even with the same seed these aren't reliably reproducible, although possibly using this seed makes it more likely that these will fail.

I've investigated a bit but can't immediately see how to fix these right now. I think the underlying issue is some kind of race condition where `File.exist?` appears to return `true` but then when we `FileUtils.rm` the file no longer exists (I may be mistaken though). Possibly the issue is that `FakeFS` is not thread-safe?
