### ISSUE TITLE
Question Loops

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#298]
There are cases where (soon-to-be) plugins will have variable data that needs to be part of the configuration. For example, the NFS plugin would want to gather all of the mount information. Currently, this is done by adding the following to `domain.yaml`:
```
nfsmounts:
  /users:
    defined: true
    server: 10.10.0.3
    export: /export/users
  /data:
    defined: true
    server: 10.10.0.3
    export: /export/data
    options: intr,sync,rsize=32768,wsize=32768,_netdev
```

With the `configure.yaml` it would be great to specify a set of questions that can be repeated, these would request:

- Mount name
- Defined?
- Server IP
- Export Dir

And store all of these within a parent for the NFS mounts.
