### ISSUE TITLE
Boolean questions not re-asked on initial `configure`

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#329]
`plugins/flightdirect/configure.yaml` has the following:
```
questions:
  - &flightdirect_isserver
    identifier: flightdirect_isserver
    question: 'Is a login node?'
    type: 'boolean'

  - &flightdirect_isclient
    identifier: flightdirect_isclient
    question: 'Is a compute node?'
    type: 'boolean'

domain:
  - *flightdirect_isserver
  - *flightdirect_isclient
```
And when I run through `metal configure domain` I get:
```
Should 'flightdirect' plugin be enabled for domain? (35/64) [yes/no]
yes
[flightdirect] Is a login node? (36/64) [yes/no]
nl
[flightdirect] Is a compute node? (37/64) [yes/no]
erhegerg
```
It just seems to accept these answers instead of prompting for a valid boolean. Does it just default to false in this case? I feel like it should prompt for an answer that's valid, like when entering no answer for a question:
```
Should 'flightdirect' plugin be enabled for domain? (35/64) [yes/no]
yes
[flightdirect] Is a login node? (36/64) [yes/no]

Please enter "yes" or "no".
[flightdirect] Is a login node? (36/64) [yes/no]

```
